export const GET_COUNTRIES = "GET_COUNTRIES";
export const ORDER_NAME = "ORDER_NAME";
export const ORDER_POPULATION = "ORDER_POPULATION";
export const FILTER_CONTINENT = "FILTER_CONTINENT";
export const FILTER_ACTIVITY = "FILTER_ACTIVITY";
export const PAGINATION = "PAGINATION";
export const SEARCH_COUNTRY = "SEARCH_COUNTRY"
export const GET_ACTIVITIES = "GET_ACTIVITIES"